Generate `ZincPlainFile` during `-sourcepath` workflow
sbt/zinc pull request #1309
Opened 2023-12-15 07:24 UTC by Friendseeker

This PR fixes #1304, #963

### Issue

https://github.com/sbt/zinc/blob/5eb0de1fdfd921f0d1b6a9302fe42593e7e27922/internal/compiler-bridge/src/main/scala/xsbt/API.scala#L62

In certain codepath, `unit.source.file` is a `PlainFile`, which causes a `MatchError`.

### Fix

When `unit.source` is built, convert `unit.source.file` to `ZincPlainFile`.

### Validating the fix

The PR includes reproduction scripted test by [lrytz](https://github.com/lrytz). The test passes after the fix.

2023-12-15 07:33 UTC, Friendseeker commented on internal/compiler-bridge/src/main/scala/xsbt/CallbackGlobal.scala
> +        new ZincPlainFile(vf.asInstanceOf[PathBasedFile])
The conversion logic is... hacky.

I would appreciate any feedback suggesting a better solution.

2024-01-03 11:02 UTC, dwijnand requested changes
See https://github.com/sbt/zinc/issues/1304#issuecomment-1875188256

2024-01-03 11:02 UTC, dwijnand commented on internal/compiler-bridge/src/main/scala/xsbt/CallbackGlobal.scala
> +        }
I think this is `AbstractZincFile(callback3.toVirtualFile(plainFile.file.toPath))`, btw.

2024-09-30 16:20 UTC, eed3si9n approved these changes

2024-10-09 22:50 UTC, Friendseeker commented
@eed3si9n While the PR is in `Changes requested` status, would it be possible for you to dismiss the stale review and force merge it if everything looks okay?

My concern is that since this PR involves `AnalysisCallback3` and https://github.com/sbt/zinc/pull/1306 is already merged in, if a Zinc release is made before the PR is merged, we would need to introduce `AnalysisCallback4`.

2024-10-11 16:07 UTC, eed3si9n commented
Yea. Now that AnalysisCallback is AnalysisCallback3, we should just land this.

2024-10-11 16:07 UTC, merged