[WIP] Zinc extract used names is very sluggish
sbt/zinc pull request #187
Opened 2016-10-20 13:19 UTC by wpopielarski

Compilation of shapeless with Zinc is very slow. Potential reason lays in
multiple visit in already traversed tree.

Please look at least at test. This file should be processed in about 5 sec. but actually takes about 5 mins.

2016-11-09 17:17 UTC, eed3si9n requested changes

2016-11-09 17:17 UTC, eed3si9n commented on internal/compiler-bridge/src/main/scala/xsbt/ExtractUsedNames.scala
>          super.traverse(tree)
Does this handle macro expansion?

2016-11-10 10:05 UTC, wpopielarski commented on internal/compiler-bridge/src/main/scala/xsbt/ExtractUsedNames.scala
>          super.traverse(tree)
sorry @eed3si9n it's not. Going to fix. Looks like there is no test to discover it.

2016-11-10 11:21 UTC, retronym commented
I would suggest to incorporate https://github.com/sbt/sbt/pull/2754 into Zinc (I've lodged https://github.com/typesafehub/zinc/issues/105 to track this work). When I profiled the slowness of Shapeless with SBT + Scala 2.12, I initially was looking at ways to optimize name extraction but eventually found out that the slowness was (mostly) due to the poor interaction with JIT.

2016-11-10 12:01 UTC, retronym commented
Actually, I see now that https://github.com/sbt/zinc/commit/33e9a507874415d4c851b8583c3387a4623b7b33 appears to introduce exponential performance by (accidentally) introducing `tt.original.foreach(traverse)` instead of `tt.original.foreach(handleNode)`.

2016-11-10 15:56 UTC, eed3si9n commented
@retronym Thanks for the detective work.

2016-11-12 04:45 UTC, eed3si9n commented
I opened https://github.com/sbt/zinc/pull/193 as a replacement for this PR.

2016-11-12 16:58 UTC, closed without merging

2016-11-12 16:59 UTC, wpopielarski commented
superseded by #193