Emulate multi-project in the scripted test
sbt/zinc pull request #208
Opened 2016-12-22 09:07 UTC by eed3si9n

2016-12-22 22:36 UTC, dwijnand requested changes

2016-12-22 22:36 UTC, dwijnand commented on internal/zinc-scripted/src/main/contraband/scripted.contra
> +package sbt.internal.inctest
If this is just to test zinc (properly, with multi-projects), can we please avoid using contraband for this?

2016-12-22 22:39 UTC, eed3si9n commented on internal/zinc-scripted/src/main/contraband/scripted.contra
> +package sbt.internal.inctest
I just need some way of describing a build-like structure like https://github.com/sbt/zinc/blob/7185554f6a17839cc2f03d6b853ebca36c99a05b/zinc/src/sbt-test/source-dependencies/binary/build.json

2016-12-22 22:41 UTC, dwijnand commented on internal/zinc-scripted/src/main/contraband/scripted.contra
> +package sbt.internal.inctest
Ok so you need to deserialise some JSON. Don't need contraband or .contra for that.

2016-12-28 21:25 UTC, dwijnand approved these changes

2016-12-28 21:26 UTC, merged