Implement used scopes for used names and implement PatMat scope
sbt/zinc pull request #267
Opened 2017-03-15 12:21 UTC by romanowski

## Motivation

In our large codebase we use sealed classes/traits a lot and we quite often adds new values to them (e.g. we represent algorithms this way). Children of such sealed classes/traits change quite often (and this is usually done by changing mixed traits) causing **all usages** of sealed classes to be recompiled.

### How we can improve zinc?

I am almost sure that (excluding macros and other non-standard) the only place where base trait is used that needs to be recompiled on change in child's type is pattern matching (to emit warning). To be more we need to invalidate all places where we match on type that contains mentioned class. Example below:

```scala
sealed trait A
object FooA
```

If we change ```FooA``` to ```FooA with Serializable``` we need to recompile all direct usages of ```FooA``` (this is not changed) but we don't need to recompile e.g. this: ```def bar(a: A) = println(a)```.

However every usage like:
```scala
def foo(a: A) = a match { ... }
def foor(b: Option[A]) = b match { ... }
```
Needs to be recompiled.

If we are using A inside ```case``` statements we don't need to recompile that usages (since warning won't be emitted in such case. Similarly if we are using unnaply to create value e.g. ```List(A, name) = myList()``` no warning will be emitted so we don't need to recompile this.

@retronym Please correct me if I am wrong since I am not compiler expert :)

## Implemetation detalis

In order to support this in zinc I created UseScope that tells about scope where name is used. So far we've got 3 scopes: ```Default```, ```Implicit``` and ```PatMat```. As you may guess current logic is implemented as ```Default```. ```Implicits``` are used so far only to find out if given class does not contains any implicit change (so is only used in API not to track implicit dependencies, but we may change this in future). Hashes are produced for each applicable scope so
 * plain ```def``` will declare hashes only in ```Default``` scopes
 * implicit class/def/val in both ```Default``` and ```Implicit```
 * sealed trait in ```Default``` and ```Implicit```

Hashes for ```Implicit``` and ```Default``` are equal (but we can change that) and for ```PatMat``` we include types of children.

If for given class only ```PatMat``` scope is changed we don't invalidate all places where only ```Default``` is used.

In future this mechanism can be used in #227 #226 

For certain reasons this time I have to paste the below disclaimer:
THIS PROGRAM IS SUBJECT TO THE TERMS OF THE BSD 3-CLAUSE LICENSE.

THE FOLLOWING DISCLAIMER APPLIES TO ALL SOFTWARE CODE AND OTHER MATERIALS CONTRIBUTED IN CONNECTION WITH THIS SOFTWARE:
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR
ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.
ONLY THE SOFTWARE CODE AND OTHER MATERIALS CONTRIBUTED IN CONNECTION WITH THIS SOFTWARE, IF ANY, THAT ARE ATTACHED TO (OR OTHERWISE ACCOMPANY) THIS SUBMISSION (AND ORDINARY
COURSE CONTRIBUTIONS OF FUTURES PATCHES THERETO) ARE TO BE CONSIDERED A CONTRIBUTION. NO OTHER SOFTWARE CODE OR MATERIALS ARE A CONTRIBUTION.

2017-03-15 12:25 UTC, romanowski commented
I will include benchmark results soon.

2017-03-15 12:26 UTC, romanowski commented on internal/zinc-persist/src/main/scala/sbt/internal/inc/EnumSetSerializer.scala
> +case class EnumSetSerializer[E <: Enum[E]: ClassTag](allValues: Array[E]) {
This is quite naive approach. I am open for suggestion about possible alternatives.

2017-03-15 12:29 UTC, jvican commented on internal/zinc-persist/src/main/scala/sbt/internal/inc/EnumSetSerializer.scala
> +case class EnumSetSerializer[E <: Enum[E]: ClassTag](allValues: Array[E]) {
This is scary...

2017-03-15 13:32 UTC, romanowski commented on internal/zinc-persist/src/main/scala/sbt/internal/inc/EnumSetSerializer.scala
> +case class EnumSetSerializer[E <: Enum[E]: ClassTag](allValues: Array[E]) {
But works :) As said I am open for suggestions.

2017-03-16 11:26 UTC, jvican requested changes
Hey @romanowski, I didn't want to yak shave so I've just pushed a commit that fixes some questions/concerns I had. More info in the commit message.
  
These changes look great and I'm happy to merge them! I have some questions first, though:
  
1. The provided tests are great, but we should have several scripted tests to check that this actually has the right behaviour. Can you please do that?
2. It seems you've glossed over extractors in pattern matching targets. It would be great if you include them in the tests and make sure they work (make sure to check that nested extractors work too).
3. The analysis that you provide in this PR for pattern matching is not as smart as it could be, if I understand these changes correctly. For instance:
```scala
def foo(a: A) = a match { ... }
```
  
This has to be recompiled iff the pattern match is exhaustively checking every possible child. If you have the following body `a match { case a2: SubTypeOfA => ???; case a: A => ??? }`, you don't need to recompile it since there's a default case that covers all the subtypes of A. You can generalize this as: "whenever there's a default case that covers the sealed super type, it's safe to ignore recompilation".
  
Please, confirm if this is an issue with your PR. The way I see this right now, it looks like the usability of these changes is not that great because if you `a` in the previous pattern match is `A` and not `Any`, you will always recompile. Perhaps I'm wrong and I didn't understand these changes well enough, though.
  
You don't have to do this in this PR, this is already an improvement over what we had before. We can do it as a follow up. I'm happy to implement it.
  
That aside, serialisation is far than ideal, but there's no clear escape, so I'm fine with that :wink:.

2017-03-16 11:26 UTC, jvican commented on internal/zinc-core/src/main/scala/sbt/internal/inc/ClassFileManagers.scala
> +object ClassFileManagers {
Why this change to the API? I suggest we leave it as it was before since it's a "companion object" of `ClassFileManager`. I'm open to changing the name in other PR, but I don't see the motivation for this name change here.

2017-03-16 11:26 UTC, jvican commented on internal/zinc-core/src/main/scala/sbt/internal/inc/IncrementalNameHashing.scala
> +      val aNameHashes = a.nameHashes()
`nameHashes` returns something, no? I think it's safe to leave the parens as they were :smile:.

2017-03-16 11:26 UTC, jvican commented on internal/zinc-core/src/main/scala/sbt/internal/inc/IncrementalNameHashing.scala
> +           |\t$byTransitiveInheritance $byLocalInheritance $byMemberRef
New lines? 💃

2017-03-16 11:26 UTC, jvican commented on internal/zinc-apiinfo/src/main/scala/xsbt/api/HashAPI.scala
> -      finalizeHash
Why don't we finalize hash here?

2017-03-16 11:35 UTC, romanowski reviewed
@jvican Thanks for that.

I see that you don't like pattern matching on null but I am fine with that.

The only thing we should change is manetioned vals (to defs).

2017-03-16 11:35 UTC, romanowski commented on internal/compiler-bridge/src/main/scala/xsbt/ExtractUsedNames.scala
> +            else existingScopes.addAll(topLevelScopes)
This emits warning. That is why I added ```()``` in the end.

2017-03-16 11:35 UTC, romanowski commented on internal/compiler-bridge/src/main/scala/xsbt/ExtractUsedNames.scala
> +  private val DefaultScopes = EnumSet.of(UseScope.Default)
EnumSets are mutable so both this vals should be defs

2017-03-16 11:35 UTC, romanowski commented on internal/compiler-bridge/src/main/scala/xsbt/ExtractUsedNames.scala
> +            else existingScopes.addAll(topLevelScopes)
BTW this is quite strange to do a review in your own PR :)

2017-03-16 11:36 UTC, jvican commented on internal/compiler-bridge/src/main/scala/xsbt/ExtractUsedNames.scala
> +            else existingScopes.addAll(topLevelScopes)
Yeah, I've realised that.

2017-03-16 11:37 UTC, jvican commented on internal/compiler-bridge/src/main/scala/xsbt/ExtractUsedNames.scala
> +  private val DefaultScopes = EnumSet.of(UseScope.Default)
Thanks for the tip, this was not clear to me!

2017-03-16 11:38 UTC, jvican commented
I'm trying to see why my commit fails in CI. The compiler error makes no sense since I haven't changed anything in compat infrastructure:
  
```
[error] /home/travis/build/sbt/zinc/internal/compiler-bridge/src/main/scala/xsbt/ExtractUsedNames.scala:276: value hasSymbolField is not a member of ExtractUsedNames.this.global.Tree

[error]       case t if t.hasSymbolField =>

[error]                   ^
```

2017-03-16 11:39 UTC, jvican commented on internal/compiler-bridge/src/main/scala/xsbt/ExtractUsedNames.scala
> +            else existingScopes.addAll(topLevelScopes)
Oh, this is by no means my PR, it's yours @romanowski.

2017-03-16 11:57 UTC, jvican commented
Oh, I almost forgot @romanowski. Post the benchmarks when you have them, I'm curious to see the results. Here you go with some instructions on how to run them: https://github.com/sbt/zinc/blob/1.0/CONTRIBUTING.md.
  
I would use the Scala standard library, you can cherry-pick its benchmarks [from this commit](https://github.com/scalacenter/zinc/commit/3da86c61c6f90dd8cb6aee1b742d49ffdd87fd6a).

2017-03-16 12:40 UTC, romanowski commented on internal/compiler-bridge/src/main/scala/xsbt/ExtractUsedNames.scala
> +            else existingScopes.addAll(topLevelScopes)
Don't worry, I don't care about that much :)

2017-03-16 12:48 UTC, jvican commented on internal/compiler-bridge/src/main/scala/xsbt/ExtractUsedNames.scala
> +            else existingScopes.addAll(topLevelScopes)
I prefer to push changes and then discuss them, than discussing them and forcing you to spend time on it. It's just more efficient :wink:.

2017-03-18 11:38 UTC, romanowski commented
[Benchmarks](https://github.com/sbt/zinc/files/852359/benchmarks.txt) as promised. I've also have full outputs if needed.

2017-03-18 13:48 UTC, romanowski commented on internal/zinc-apiinfo/src/main/scala/xsbt/api/HashAPI.scala
> -      finalizeHash
To keep API unified and force users to use HashApi.apply.

2017-03-18 14:03 UTC, romanowski commented
Regarding @jvican review:

1. My tests are more or less scripted tests done in Scala code but I will also add some scripted ones (since they are quite easy to add).

2. I don't know if I get this correctly. Do you want me to include a tests for cases like one below?
```scala
val List(Option(SealedChildren1(a)), None, Some(b: Sealed), Some(SealedChildren2(c)) = ???
```
3. You are right, this is quite simple solution. So it should say that  child of sealed trait/class changed zinc recompiles **every place where warning can be reported**.  So there is a lot of space to improve that (the only thing we need to do is to improve mechanism to decide if we depend on given name in PatMat Scope). Good and quite cheap and easy to implement option will be check if default case is provided.

2017-03-19 08:44 UTC, jvican commented
> I don't know if I get this correctly. Do you want me to include a tests for cases like one below?
  
Yes, that's right, and the same for `@`:
  
```scala
any match {
  case s @ Some(value) =>
  case None =>
```

2017-03-19 08:46 UTC, jvican commented
I will have a look at the benchmarks soon, I'm now unavailable. Thanks for responding to all the feedback @romanowski.

2017-03-19 23:37 UTC, retronym commented on internal/compiler-bridge/src/main/scala/xsbt/ExtractUsedNames.scala
> +        PatMatDependencyTraverser.traverse(tpt.tpe)
Looking at the types of synthetic case vals seems like a fairly robust way to find usages of sealed-ness. As you mentioned, this doesn't cover hidden dependencies from macros (e.g.. shapeless `Generic`). As long as we provide configuration to let people enable/disable this optimization, that's okay in my view.

2017-03-20 19:58 UTC, jvican commented
Benchmark results on this one look great, there's a small decrease of 300s in p95, but we can live with it.
  
Last thing on this PR before proposing it to merge it: can we add an option to `IncOptions` that enables/disables this mode as Jason suggests?
  
In the long term, when the support for sealed classes detection improves, we can make it by default. For now, though, this PR may undercompile under some scenarios (macro dependencies) while before we were overcompiling. We know macro dependencies are not common, but we should try to protect users from any case in which Zinc undercompiles.

2017-03-20 21:53 UTC, romanowski commented
Option added and optimization is off by default.

2017-03-27 05:09 UTC, jvican commented
Perfect, this is good to go @romanowski. I'll push the approve button in a few hours, I'm in mobile now. Can someone else have a look at this patch? @eed3si9n @dwijnand

2017-03-27 12:10 UTC, jvican approved these changes

2017-03-27 18:16 UTC, eed3si9n submitted a review, later dismissed

2017-03-27 18:16 UTC, eed3si9n commented on internal/compiler-interface/src/main/java/xsbti/UseScope.java
> +    Default, Implicit, PatMatTarget
Could we add documentation on what these scopes represent?

2017-03-27 18:17 UTC, eed3si9n commented
Minor comments, but overall looks good. Nice work!

2017-03-28 20:38 UTC, romanowski commented
Added some documentation to `UseScope`.

Also backported some small changes from our integration (ClassloaderCache can save us even 10% of compilation time, this is amazing!).

2017-03-28 23:23 UTC, dwijnand approved these changes

2017-03-28 23:24 UTC, merged

2017-03-29 06:14 UTC, jvican commented
> In future this mechanism can be used in #227 #226

Please, let's avoid this kind of statements without further double checking with maintainers. I explained in the Gitter channel that this is not correct, and this can lead to confusion as shown in #226 and #227.