Reformat with scalafmt
sbt/zinc pull request #294
Opened 2017-04-25 09:40 UTC by jvican

The following commit follows the formatting convention established upstream in sbt/sbt.

2017-04-25 09:41 UTC, jvican commented
I suggest to merge this after the open PRs.

2017-04-25 09:44 UTC, dwijnand commented
.scalafmt.conf is missing

2017-04-25 09:45 UTC, dwijnand requested changes

2017-04-25 09:45 UTC, dwijnand commented on internal/compiler-bridge/src/main/scala/xsbt/Command.scala
> +import scala.tools.nsc.{CompilerCommand, Settings}
This (and other examples) don't convince me we're really using the same configuration here..

2017-04-25 09:46 UTC, jvican commented
> .scalafmt.conf is missing
  
Oh shoot, forgot to add it when rebasing from another branch.

2017-04-25 09:47 UTC, jvican commented
I've just updated the PR, thanks for the catch @dwijnand.

2017-04-25 09:56 UTC, dwijnand requested changes

2017-04-25 09:56 UTC, dwijnand commented on internal/compiler-bridge/src/main/scala/xsbt/DelegatingReporter.scala
> +        case _ => ""
why are these not aligned?

NB when changing scalafmt config you can't just reformat again - you need to format from the original source code, then the result will correctly reflect the specified configuration.

2017-04-25 11:04 UTC, jvican commented on internal/compiler-bridge/src/main/scala/xsbt/DelegatingReporter.scala
> +        case _ => ""
The last commit aligns them :smile:

2017-04-25 12:06 UTC, dwijnand requested changes
Added some random comments, mostly for Olaf.

But the thing missing here for me is CI enforcement of the format.

2017-04-25 12:06 UTC, dwijnand commented on internal/zinc-apiinfo/src/main/scala/xsbt/api/APIUtil.scala
> +    ) | x(isMacro, 6)).toByte
lol

2017-04-25 12:06 UTC, dwijnand commented on internal/zinc-apiinfo/src/main/scala/xsbt/api/Discovery.scala
> +    }.toSet
Is this a scalafmt bug? It's sub 100 columns (it's 62). /cc @olafurpg

2017-04-25 12:06 UTC, dwijnand commented on internal/zinc-compile-core/src/main/scala/sbt/internal/inc/LoggerReporter.scala
> +  }
This is weird too. 57 cols < 100 cols. /cc @olafurpg

2017-04-25 14:28 UTC, jvican commented
> But the thing missing here for me is CI enforcement of the format.
  
There is CI enforcement of the format via `scalafmtCheck`. But users will need to make sure all sources are compiled by running scalafmt manually or via their IDE.

2017-04-25 15:48 UTC, olafurpg commented on internal/zinc-apiinfo/src/main/scala/xsbt/api/APIUtil.scala
> +    ) | x(isMacro, 6)).toByte
See http://scalameta.org/scalafmt/#Infixapplications line breaks around infix operators are your responsibility, so in this case scalafmt won't insert a line break before or after `|`

2017-04-25 15:48 UTC, olafurpg commented on internal/zinc-apiinfo/src/main/scala/xsbt/api/Discovery.scala
> +    }.toSet
Scalafmt is too eager at breaking down curly brace lambdas. I've known about this for a long time and iirc someone complained about it on gitter sometime but it has never been reported. I suspect it's not too hard to fix, so I invite you to open an issue ;)

However,  scalafmt will not try to move a curly brace lambda into a single line if there already is a newline inside the block.

2017-04-25 15:48 UTC, olafurpg commented on internal/zinc-compile-core/src/main/scala/sbt/internal/inc/LoggerReporter.scala
> +  }
Same as above, scalafmt doesn't seem to like single line curly brace lambdas at all 😅

2017-04-25 16:30 UTC, dwijnand commented on internal/zinc-apiinfo/src/main/scala/xsbt/api/APIUtil.scala
> +    ) | x(isMacro, 6)).toByte
Oh I know the problem. I'm sure over the coming time while I work on a codebase with scalafmt enforcement (:tada:) I'll get motivated enough to try and contribute an improvements in this area to scalafmt :)

2017-04-25 16:35 UTC, dwijnand commented on internal/zinc-apiinfo/src/main/scala/xsbt/api/Discovery.scala
> +    }.toSet
https://github.com/scalameta/scalafmt/issues/913

2017-04-25 16:35 UTC, dwijnand commented
`scalafmtCheck` just runs git, so nothing is enforcing the format, right? Or am I missing something?

2017-04-25 16:36 UTC, jvican commented
> scalafmtCheck just runs git, so nothing is enforcing the format, right? Or am I missing something?
  
Gimme a sec, doing changes to the whole design :wink:.

2017-04-25 18:09 UTC, jvican commented
I've just updated this PR with the same changes as https://github.com/sbt/sbt/pull/3141.

2017-05-03 16:36 UTC, jvican commented
This has been completely updated as per https://github.com/sbt/librarymanagement/pull/87. Please review.

2017-05-03 16:57 UTC, eed3si9n requested changes

2017-05-03 16:57 UTC, eed3si9n commented on build.sbt
> +  disablePlugins(com.typesafe.sbt.SbtScalariform).
Why don't we just remove scalariform from the build?

2017-05-03 16:58 UTC, jvican commented on build.sbt
> +  disablePlugins(com.typesafe.sbt.SbtScalariform).
Because it's not directly in the build, sbt house-rules depends on it.

2017-05-03 16:59 UTC, eed3si9n commented on build.sbt
> +  disablePlugins(com.typesafe.sbt.SbtScalariform).
I see. That makes sense.

2017-05-03 16:59 UTC, eed3si9n approved these changes

2017-05-03 17:00 UTC, eed3si9n commented
LGTM

2017-05-03 17:03 UTC, eed3si9n commented
I've opened https://github.com/sbt/sbt-houserules/issues/15

2017-05-03 17:04 UTC, dwijnand requested changes
This is missing CI enforcement.

2017-05-03 17:07 UTC, jvican commented
Well spotted @dwijnand. I had it in unstaged! Just pushed.

2017-05-04 01:44 UTC, eed3si9n commented
```
[error] Expected configuration
[error] Expected ':' (if selecting a configuration)
[error] Expected key
[error] Expected '::'
[error] Expected end of input.
[error] zincScripted/test zinc/test zincPersist/test zincIvyIntegration/test zincTesting/test scalafmtCheck
[error]                  ^
```

2017-05-04 09:44 UTC, dwijnand approved these changes
Good to go.

2017-05-04 09:44 UTC, merged