Add the first iteration of the Zinc API 1.0
sbt/zinc pull request #304
Opened 2017-05-22 16:59 UTC by jvican

This is just the first iteration of the Zinc API.
  
This iteration had as a goal to do a first step in making public safe functionality of Zinc to allow Scala and Java parties (Gradle, Pants, Maven, et cetera) use Zinc with binary compatibility guarantees. This task needs another iteration given:
  
1. The big surface of the API; and,
2. The fact that the whole Zinc API was made private for 1.0.

The last iteration will happen before RC1 (end of June - beginning of July).
  
The new public API makes it easier to:
  
* Get a compiled bridge for a given scala instance (via ivy).
* Get a scala instance (via ivy).
* Instantiate a Zinc compiler.
* Provide utilities for both Java and Scala users to get default implementations that do not expose the internals, placed in `sbt.internal.inc`.
  
Aside from these, this API also addresses some issues that have arisen in the past:
  
* It makes it easier to customize the classfile manager, as required by Scalajs and Scala Native. https://github.com/sbt/zinc/issues/125
* It replaces any instance of Maybe with Optional. https://github.com/sbt/zinc/issues/302
 
I find that in general, these commits make Zinc easier to use and improve the consistency of the whole API. The most remarkable change is the `CompileAnalysis` API, which now provides useful information for build tools like file stamps, compilations and source infos.
  
Note that all the utilities made public only expose functionality that is a product of the incremental compiler. No internal details of the incremental analysis are exposed to the users.
  
There are some Java files that have been moved out of the compiler interface because they required static method implementations in the projects on which the implementations of certain classes were provided.
  
In the future, I feel that these are the things that should be worked on to finish off the Zinc API:
  
1. Reorder project structure. Simplify it and make it more granular and easier to test. https://github.com/sbt/zinc/issues/286
2. Decide what and how to use to persist analysis files with appropriate benchmarking. https://github.com/sbt/zinc/issues/268 (protobuf is not possible, so we need to find a way to either use sbinary or a similar solution that does not harm (or even improve!) speed of compiler iterations).
3. Create utilities to instantiate:
  3.1. Empty `Analysis`.
  3.2. `DefinesClass`.
  3.3. `AnalysisStore` (up to discussion for next iteration).
  3.4. `JavaTool` et al, necessary to create `Compilers`.
  3.5. `PerClasspathLookupEntry`.
4. Make analysis content machine-independent: #218
  
I have more ideas, but those will be discussed when time's up.

The breaking changes are documented in every commit. I suggest that reviewers go through the commits one by one, though I don't expect them to do so (given the big diff size). As this is just the first iteration of the redesign and targets a milestone, I am not writing any migration notes for now. I'll wait until everything is finished in our first RC to write the migration notes so that other build tools (other than sbt) can start using it.
  
As a reminder, the public API is `xsbti`. Scala implementations live in `sbt.internal.inc`.
  
This is a good time to gather feedback. So that's very much welcome.

2017-05-24 02:53 UTC, eed3si9n commented
As a test, could we put `zinc/src/test/scala/sbt/inc/*Spec.scala` into another package name like `com.example`, and see if it's able to initialize everything without invoking the internals?

While I agree with getting rid of `Maybe` and using `Optional` it's a bit distracting to review it because it spans across everywhere. How difficult do you think it would be to split Maybe change into a another PR that precedes this?

2017-05-24 03:28 UTC, eed3si9n requested changes
Some minor comments.

2017-05-24 03:28 UTC, eed3si9n commented on internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/Build.scala
> -final class Build private (
What happened to my build.json?

2017-05-24 03:28 UTC, eed3si9n commented on internal/compiler-interface/src/main/java/xsbti/compile/CompilerBridgeProvider.java
> +    File getBridgeSources(ScalaInstance scalaInstance, Logger logger);
Getter shouldn't have side effects.

2017-05-24 03:28 UTC, eed3si9n commented on internal/zinc-ivy-integration/src/main/scala/sbt/internal/inc/IfMissing.scala
> +sealed trait IfMissing
Not sure why this needs to be on its own file.

2017-05-24 03:28 UTC, eed3si9n commented on internal/compiler-interface/src/main/java/xsbti/compile/CompilerBridgeProvider.java
> +            public File getCompiledBridge(ScalaInstance scalaInstance, Logger logger) {
Same as before. Getter shouldn't have side effects.

2017-05-26 13:20 UTC, jvican commented on internal/zinc-ivy-integration/src/main/scala/sbt/internal/inc/IfMissing.scala
> +sealed trait IfMissing
We may want to explore to make this stable in the next iteration. That's why I split it up, there was too much logic in its place of origin.

2017-05-26 13:20 UTC, jvican commented on internal/compiler-interface/src/main/java/xsbti/compile/CompilerBridgeProvider.java
> +    File getBridgeSources(ScalaInstance scalaInstance, Logger logger);
I'll call it `fetchBridgeSources`.

2017-05-26 13:22 UTC, jvican commented
> As a test, could we put zinc/src/test/scala/sbt/inc/*Spec.scala into another package name like com.example, and see if it's able to initialize everything without invoking the internals?
  
This is a good idea. I'ld like to do this in the second iteration, since there are still some things that must be got from `internal`. Those I specify in the PR description, but I may be missing more.
  
> While I agree with getting rid of Maybe and using Optional it's a bit distracting to review it because it spans across everywhere. How difficult do you think it would be to split Maybe change into a another PR that precedes this?
  
The diff for the maybe migration is small, see https://github.com/sbt/zinc/pull/304/commits/686b6bb174fe76390646a7e7770914906fefc2f1. For time-consuming reasons, I would prefer to get it merged in this PR.

2017-05-26 13:23 UTC, jvican commented on internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/Build.scala
> -final class Build private (
This has been recovered.

2017-05-26 13:33 UTC, jvican commented
Feedback has been addressed @eed3si9n.

2017-05-26 14:03 UTC, jvican commented
Tests are green.

2017-05-26 19:22 UTC, eed3si9n approved these changes

2017-05-26 19:24 UTC, eed3si9n commented
Thanks for all the work on this.

2017-05-26 19:24 UTC, merged

2017-06-07 22:58 UTC, stuhood commented
With regard to additional private/internal APIs that are currently in use, can browse through https://github.com/pantsbuild/pants/tree/master/src/scala/org/pantsbuild/zinc (as of zinc `1.0.0-X7`) ... I'm currently working on updating to include this patch.

2017-06-08 14:01 UTC, jvican commented
@stuhood I've been browsing through that for a while, but thanks for the heads up. Are you in a hurry to do this? I'll be tackling the second iteration of the API soon before the release candidate and the API freeze, so maybe you want to wait until that's out?

2017-06-08 14:04 UTC, eed3si9n commented
The change I made to sbt is https://github.com/sbt/sbt/pull/3228

2017-06-09 01:15 UTC, stuhood commented
@jvican : It would probably make sense for me to continue to attempt this, just in order to find any additional issues that you might not have seen. As an example, yesterday I noticed that it's not currently possible to extend `LoggerReporter` in a useful way, because various methods were made private. So https://github.com/pantsbuild/pants/blob/master/src/scala/org/pantsbuild/zinc/logging/Reporters.scala#L28 is no longer possible.

2017-06-12 21:03 UTC, jvican commented
> So https://github.com/pantsbuild/pants/blob/master/src/scala/org/pantsbuild/zinc/logging/Reporters.scala#L28 is no longer possible. A theoretical FilteredReporter wrapper might make more sense anyway though.
  
Great, I'll make this (or something similar, I have to look into the details) happen to unblock that implementation.

2017-06-16 23:49 UTC, stuhood commented
@jvican: A few more details here:
1. the Reporter API seems to require a `ManagedLogger`, but it's not clear how (or whether it would be a good idea) to create one of those, versus passing in an `xsbti.Logger` or `sbt.util.Logger`
2. Because a `Reporter` is a required parameter for `IncrementalCompilerImpl.compile` (and there doesn't appear to be a way to create a `LoggerReporter` without a `ManagerLogger`), it does not currently seem to possible to compile using the 18 arg form.

I'm going to try porting to usage of `xsbti.Inputs` instead.

2017-06-19 23:27 UTC, stuhood commented
Alright, I ported to `xsbti.compile.Inputs`, and it cleared things up considerably. But the above issue with `LoggerReporter` and `ManagedLogger` is still an issue.

Also, it doesn't look like it's possible to use a "default" Reporter (as it is with `Progress`, which is `Optional`)... it's conceivable that at some point in the future we'll move the log filtering out of the Reporter, at which point being able to use the default would be good.

2017-06-20 10:43 UTC, jvican commented
@stuhood: Yes, it seems that the entanglement between `LoggerReporter` and `ManagedLogger` is due to sbt. It's an API where sbt's design decisions leak too much.
  
To overcome this issue, some of Zinc's test suites create a `ConsoleReporter` that is a direct subclass of `Reporter` and just `println`s, but that's far from desirable. I think I am going to create a `ManagedLogger` for Zinc and expose it somewhere, or at least make it trivial to create a Zinc reporter. I am working on it as we speak.
  
With regards to making the reporter `Optional`, I have my doubts this is the best choice. It's such a key component of the compilation that I would prefer that users explicitly pass it. Also, depending on the use case, it's likely to be changed. What is a safe assumption for the user? Will Zinc output to my console? Since it's not obvious, I believe users may be better off being more explicit about what they want. I guess that you need for this would disappear if we add methods to instantiate zinc reporters that you can pass in. WDYT?

2017-06-20 11:18 UTC, jvican commented
For the record, if you want to move forward and need a `ManagedLogger`, you can do `sbt.util.LoggerExchange.logger(...)`.

2017-06-20 20:44 UTC, stuhood commented
> What is a safe assumption for the user? Will Zinc output to my console? Since it's not obvious, I believe users may be better off being more explicit about what they want. I guess that you need for this would disappear if we add methods to instantiate zinc reporters that you can pass in. WDYT?

Yea, that makes sense. I'm still thinking of zinc as a CLI tool, but in the context of a library, being explicit about output location is important... ditto logging.

2017-06-22 15:33 UTC, jvican commented
Hey @stuhood, I've been fixing all the issues you've reported regarding logging. I think I have come up with some elegant solutions you may want to have a look at.

This is the most important change: https://github.com/scalacenter/zinc/commit/a9a9c2faf3b511c0f95b19fab87eea2e67346408.
  
All the changes are in this branch: https://github.com/sbt/zinc/compare/1.0...scalacenter:fix-loggers.
  
I can release these changes as part of a temporary `scalacenter/zinc` release to unblock you and get more feedback. These changes will need, of course, to be merged upstream in sbt/zinc.
  
In the new interface, I have added a filtered reporter in Zinc and the normal `LoggerReporter` (now renamed to `LoggedReporter`, see https://github.com/scalacenter/zinc/commit/cac014918ec6d4ff20b257d8363256739d5645e1). `LoggedReporter` now accepts `xsbti.Logger`, meaning that you can pass in whatever logging mechanism you want so long as it extends that interface. These reporter implementations are internal, but you can get a reporter backed up by a logger via the public `ReporterUtil`: https://github.com/scalacenter/zinc/commit/60820b18b7d56f0b7c9e9a9ae267c2e5bc50b59c.
  
Let me know if this public API works for you.

2017-06-24 00:37 UTC, stuhood commented
Thanks @jvican . The API looks great (with one exception mentioned below): thanks for incorporating file/msg based filtering.

I should be able to sanity check incremental compile before the end of Monday.

There is a bit of inconsistency between `java.util.function.Function` and `xsbti.F1` for positionMappers in `ReporterUtil` and `CompileOptions`. pants currently only requires JDK7, but I'm floating the idea of switching to JDK8 now... `Function` should be fine, but consistency would be good.

2017-06-25 08:43 UTC, jvican commented
@stuhood Happy that you mention that, I opened a PR in sbt/util to address that issue three days ago. The idea is to remember any trace of the old Java-friendly classes for bincompat (`F0`, `F1` and `Maybe`) and replace them by the default Java ones (`Supplier`, `Function` and `Optional`).
https://github.com/sbt/util/pull/84

2017-06-26 03:46 UTC, stuhood commented
The new API looks good from a logging/usability perspective (other than #317). I have things working well enough to have reproduced https://github.com/pantsbuild/pants/issues/4477, so I will begin debugging that tomorrow.

2017-06-27 20:16 UTC, stuhood commented
@jvican : If you have a PR for the `Reporters`/`Logger` change, I'd shipit. I'm getting close to needing an `X17` release to move forward.

2017-06-27 21:56 UTC, jvican commented
Shipping it tomorrow morning. It's ready but kept it local because I'm changing more things in the API.