[Do not merge] Adapt Zinc to use the new LibraryManagement API
sbt/zinc pull request #335
Opened 2017-07-06 13:42 UTC by Duhemm

Depends on sbt/librarymanagement#124.

2017-07-06 13:42 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/335/head&deploy_to_bintray=false">this link.</A>

2017-07-06 13:43 UTC, typesafe-tools commented
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/75/console">is in progress...</a>

2017-07-06 13:45 UTC, typesafe-tools commented
[//]: # (Refs: 1.0.x-pull/335/head-1.0-pull/125/head-1.0-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/75/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | 1.0.x                | sbt/sbt@d464383722ef736376dc85e3f052826c6f627d23
  zinc              | pull/335/head        | sbt/zinc@79f8e0c47ee0963f54bd14b8817eebea26a5fb01
  io                | 1.0                  | sbt/io@21ed6ec2a2e33fd88a5f013f643d04fda26de4de
  librarymanagement | pull/125/head        | sbt/librarymanagement@9d1b8de2ff4c89e96267308af5271288592ff0ad
  util              | 1.0                  | sbt/util@c76d2624f931a2b75453f39dcaaf750bf4282a44
  website           | 1.0.x                | sbt/website@7e644bc8fc623589152e98bee75afd44893690e3

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=1.0.x&zinc=pull/335/head&io=1.0&librarymanagement=pull/125/head&util=1.0&website=1.0.x&deploy_to_bintray=false">(restart)</A>

2017-07-06 13:50 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/335/head&deploy_to_bintray=false">this link.</A>

2017-07-06 13:51 UTC, typesafe-tools commented
A dbuild validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/76/console">is in progress...</a>

2017-07-06 13:52 UTC, typesafe-tools commented
[//]: # (Refs: 1.0.x-pull/335/head-1.0-pull/125/head-1.0-1.0.x)
dbuild <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/76/">has checked</A> the following projects against Scala 2.12:

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | 1.0.x                | sbt/sbt@d464383722ef736376dc85e3f052826c6f627d23
  zinc              | pull/335/head        | sbt/zinc@bde9b92ad058e930f560c2ad45a8a43a35610aec
  io                | 1.0                  | sbt/io@21ed6ec2a2e33fd88a5f013f643d04fda26de4de
  librarymanagement | pull/125/head        | sbt/librarymanagement@9d1b8de2ff4c89e96267308af5271288592ff0ad
  util              | 1.0                  | sbt/util@c76d2624f931a2b75453f39dcaaf750bf4282a44
  website           | 1.0.x                | sbt/website@7e644bc8fc623589152e98bee75afd44893690e3

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild?sbt=1.0.x&zinc=pull/335/head&io=1.0&librarymanagement=pull/125/head&util=1.0&website=1.0.x&deploy_to_bintray=false">(restart)</A>

2017-07-06 14:00 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/335/head&deploy_to_bintray=false">this link.</A>

2017-07-07 15:12 UTC, jvican requested changes
Looking forward to this passing CI. I just have one question. The rest of changes LGTM!

2017-07-07 15:12 UTC, jvican commented on project/Dependencies.scala
> +  private val lmVersion = "1.0.0-SNAPSHOT"
Can we depend on a stable version?

2017-07-07 15:52 UTC, Duhemm commented on project/Dependencies.scala
> +  private val lmVersion = "1.0.0-SNAPSHOT"
That's the plan once the new library management API is merged and released.

2017-07-12 14:22 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/335/head&deploy_to_bintray=false">this link.</A>

2017-07-12 18:44 UTC, eed3si9n requested changes

2017-07-12 18:44 UTC, eed3si9n commented on internal/zinc-ivy-integration/src/main/scala/sbt/internal/inc/ZincComponentCompiler.scala
> +        libraryManagement.moduleDescriptor(wrapper, dependencies, None)
Component is no longer part of the configurations out of the box, so that might needs adjustment.

2017-07-13 09:02 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/335/head&deploy_to_bintray=false">this link.</A>

2017-07-13 09:03 UTC, Duhemm commented on internal/zinc-ivy-integration/src/main/scala/sbt/internal/inc/ZincComponentCompiler.scala
> +        libraryManagement.moduleDescriptor(wrapper, dependencies, None)
Done

2017-07-13 09:04 UTC, Duhemm commented on project/Dependencies.scala
> +  def addSbtLmIvyTest(p: Project): Project = addSbtModule(p, sbtLmPath, "lmIvy", libraryManagementIvy, Some(Test))
@eed3si9n @dwijnand I changed that when I played with dbuild. Is this necessary / correct?

2017-07-13 09:08 UTC, Duhemm commented
Should we rename the `zincIvyIntegration` module? `zincLmIntegration`?

2017-07-13 09:15 UTC, dwijnand commented on project/Dependencies.scala
> +  def addSbtLmIvyTest(p: Project): Project = addSbtModule(p, sbtLmPath, "lmIvy", libraryManagementIvy, Some(Test))
LGTM, thanks.

2017-07-13 13:31 UTC, eed3si9n commented
@Duhemm 

> Should we rename the zincIvyIntegration module? zincLmIntegration?

Yes. Let's do it.

2017-07-13 13:38 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/335/head&deploy_to_bintray=false">this link.</A>

2017-07-13 13:41 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?zinc=pull/335/head&deploy_to_bintray=false">this link.</A>

2017-07-13 13:42 UTC, Duhemm commented
Done

2017-07-13 14:06 UTC, eed3si9n approved these changes

2017-07-14 14:39 UTC, jvican commented
When is the new LM api gonna be released? This is blocking adding a new method to the public API.

2017-07-15 19:01 UTC, eed3si9n commented
LM API has been merged. I am now starting to merge PRs for Zinc locally to make sure they compile.

2017-07-15 19:48 UTC, jvican commented
Superseded by https://github.com/sbt/zinc/issues/366.

2017-07-15 19:48 UTC, closed without merging