User sbt 1.0.0-RC2 in the build
sbt/zinc pull request #378
Opened 2017-07-26 09:47 UTC by jvican

Follows up on https://github.com/sbt/zinc/pull/373.

2017-07-26 12:30 UTC, jvican commented
It seems the protoc plugin is not working for the following cases:
1. https://github.com/scalapb/ScalaPB/issues/314
2. https://github.com/scalapb/ScalaPB/issues/313
  
This PR is therefore conservative until we do solve this situation:
1. It does not upgrade the protoc plugin.
2. It does not use the compiler shaded version (**IMPORTANT**).
  
Review by @dwijnand and @Duhemm.

2017-07-26 12:33 UTC, jvican commented
Note that this adds sbt-mima.

2017-07-26 12:39 UTC, jvican commented
This PR is failing in the Ci because 2.12.3 is not yet released to Central. When it is, the CI will be run and if successful can be merged.

2017-07-26 12:41 UTC, dwijnand requested changes
There's no enforcement of MiMa in CI

2017-07-26 12:41 UTC, dwijnand commented on .drone.yml.sig
> +eyJhbGciOiJIUzI1NiJ9.cGlwZWxpbmU6CiAgIyBGZXRjaCBmb2xkZXJzIGZyb20gZGlzdHJpYnV0ZWQgY2FjaGUKICBzZnRwX2NhY2hlX3Jlc3RvcmU6CiAgICBpbWFnZTogcGx1Z2lucy9zZnRwLWNhY2hlCiAgICByZXN0b3JlOiB0cnVlCiAgICBtb3VudDoKIC
What does this do and why did it change?

2017-07-26 12:41 UTC, dwijnand commented on build.sbt
> +  resolvers += Resolver.sonatypeRepo("staging"),
I'd prefer not adding another resolver - we already have more than we should.

2017-07-26 12:50 UTC, jvican commented on build.sbt
> +  resolvers += Resolver.sonatypeRepo("staging"),
Agreed, should be removed. It slipped through the cracks.

2017-07-26 12:51 UTC, jvican commented on .drone.yml.sig
> +eyJhbGciOiJIUzI1NiJ9.cGlwZWxpbmU6CiAgIyBGZXRjaCBmb2xkZXJzIGZyb20gZGlzdHJpYnV0ZWQgY2FjaGUKICBzZnRwX2NhY2hlX3Jlc3RvcmU6CiAgICBpbWFnZTogcGx1Z2lucy9zZnRwLWNhY2hlCiAgICByZXN0b3JlOiB0cnVlCiAgICBtb3VudDoKIC
This is necessary every time the drone.yml is modified, so that attackers cannot say what your Ci does. It's a security measure.

2017-07-26 12:52 UTC, jvican commented on build.sbt
> +  resolvers += Resolver.sonatypeRepo("staging"),
Oh, no, actually this is necessary for now until Scala 2.12.3 has hit Central. I will remove it then.

2017-07-26 12:53 UTC, jvican commented
Feedback addressed.

2017-07-26 12:55 UTC, dwijnand commented on .drone.yml.sig
> +eyJhbGciOiJIUzI1NiJ9.cGlwZWxpbmU6CiAgIyBGZXRjaCBmb2xkZXJzIGZyb20gZGlzdHJpYnV0ZWQgY2FjaGUKICBzZnRwX2NhY2hlX3Jlc3RvcmU6CiAgICBpbWFnZTogcGx1Z2lucy9zZnRwLWNhY2hlCiAgICByZXN0b3JlOiB0cnVlCiAgICBtb3VudDoKIC
How do I generate it?

2017-07-26 12:55 UTC, dwijnand commented on bin/run-ci.sh
> +  mimaReportBinaryIssues \
How does this validate our 2.10 artifacts?

2017-07-26 13:00 UTC, jvican commented on bin/run-ci.sh
> +  mimaReportBinaryIssues \
Good catch, forgot to `+`.

2017-07-26 13:01 UTC, jvican commented on bin/run-ci.sh
> +  mimaReportBinaryIssues \
Check if my solution works.

2017-07-26 14:08 UTC, jvican commented on .drone.yml.sig
> +eyJhbGciOiJIUzI1NiJ9.cGlwZWxpbmU6CiAgIyBGZXRjaCBmb2xkZXJzIGZyb20gZGlzdHJpYnV0ZWQgY2FjaGUKICBzZnRwX2NhY2hlX3Jlc3RvcmU6CiAgICBpbWFnZTogcGx1Z2lucy9zZnRwLWNhY2hlCiAgICByZXN0b3JlOiB0cnVlCiAgICBtb3VudDoKIC
From the `drone` command line application. It's in the docs, v0.5.

2017-07-27 09:35 UTC, jvican commented
Rebased on top of #379, it only adds the 2.12.3 version.

2017-07-27 09:49 UTC, dwijnand approved these changes
Ah, the test is failing because Scala 2.12.3 isn't in Maven Central yet. So we can re-run this when it is to get it green and merge it.

So, LGTM. Thanks Jorge.

2017-07-28 02:08 UTC, eed3si9n approved these changes

2017-07-28 02:08 UTC, merged