Set up sbt-release-early
sbt/zinc pull request #429
Opened 2017-10-12 15:34 UTC by jvican

Builds upon sbt/zinc#428.

2017-10-12 15:34 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?zinc=pull/429/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

2017-10-17 16:16 UTC, jvican commented
f

2017-10-17 16:19 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?zinc=pull/429/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

2017-10-17 16:33 UTC, jvican commented on project/plugins.sbt
> -addSbtPlugin("com.lucidchart" % "sbt-scalafmt" % "1.12")
This is already in sbt-houserules.

2017-10-18 08:20 UTC, jvican commented
This pull request adds a cached publish local that surprisingly allows us to simplify the build by removing ad-hoc commands and workarounds (`scriptedUnpublished`). From the commit message:
```
`cachedPublishLocal` is a special task that avoids publishing if an
artifact has already been published and the publication time is greater
than the changes to the source directories.

In order to find this out, `cachedPublishLocal` resolves the artifact
intransitively and in a project-specific directory. This directory is
also the used to resolve everything from scripted. This resolution is
fast because it assumes that no other task is able to publish that jar
to that concrete resolver. As a result, this assumption allows us to
remove the global dependency lock.

Running `cachedPublishLocal` in the root directory takes from 0 to 1
second. When a new change is written into a project's source file or a
resource file, `cachedPublishLocal` publishes only the project that
received the changes. This is possible because the optimizer is not
allowed and jars are independent from each other.

In this setup, `scripted` uses `cachedPublishLocal`. `scripted`
**needs** the compiler bridges for all the Scala versions, so if you
change the bridge or this is the first time you use this setup, you must
run `+compilerBridge/cachedPublishLocal`.
```

2017-11-21 19:29 UTC, eed3si9n requested changes

2017-11-21 19:29 UTC, eed3si9n commented on build.sbt
> +    crossScalaVersions := bridgeScalaVersions,
During the release, wouldn't this result to double publishing?

2017-11-21 19:29 UTC, eed3si9n commented on build.sbt
> -// defines operations on the API of a source, including determining whether it has changed and converting it to a string
Why are we removing these comments?

2017-11-21 22:00 UTC, jvican commented on build.sbt
> -// defines operations on the API of a source, including determining whether it has changed and converting it to a string
Because it's documented in the contributing guide, better.

2017-11-21 22:05 UTC, jvican commented on build.sbt
> +    crossScalaVersions := bridgeScalaVersions,
Good question, I think it would, I'll try it tomorrow and fix it if that's the case.

2018-01-10 14:07 UTC, closed without merging