Add 1.0.5 to mimaPreviousArtifacts, & backfill
sbt/zinc pull request #471
Opened 2017-12-18 17:00 UTC by dwijnand

Remove the file exclude files before (a) compiler-bridge's exclude
file is redundant since we no longer mima-check it, and (b) it interacts
badly with multiple versions.

2017-12-18 17:00 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?zinc=pull/471/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

2017-12-19 02:38 UTC, eed3si9n submitted a review, later dismissed

2018-01-01 21:21 UTC, jvican requested changes
I think the exclusions should be handled as before. You can remove the compiler bridge exclusions and add `1.0.5` without specifying the exclusions in the sbt build file (which IMO brings us more disadvantages than advantages -- I don't want to compile my build every time I exclude a class).

2018-01-02 10:31 UTC, dwijnand commented
I tried to keep the exclusions handled as before, but the problem is when it checks for version 1.0.5 it needs all the exclusions already present in the 1.0.0 exclusions to be repeated in the 1.0.5 exclusion. So you need to duplicate the exclusion files. And copy it a bunch more times if you want to verify multiple versions like I'm doing. It seems to be a downside of the file-based approach rather than the programmatic approach.

What I propose is that we merge this as is, and discuss in the MiMa repo how to avoid the copy-and-paste issue. WDYT?

2018-01-02 15:27 UTC, jvican commented
SGTM, Dale.

2018-01-02 15:27 UTC, jvican submitted a review, later dismissed

2018-01-02 15:28 UTC, jvican commented
Can you rebase and we merge?

2018-01-02 16:27 UTC, merged