Address #349: Rename the imported classes
sbt/zinc pull request #487
Opened 2018-02-11 12:14 UTC by exoego

This PR partially addresses https://github.com/sbt/zinc/issues/349 by resolving ```imported `Foo` is is permanently hidden by definition of object Foo in package bar``` warnings such as

> [warn] /home/exoego/IdeaProjects/zinc/internal/zinc-core/src/main/scala/sbt/internal/inc/AnalysisStore.scala:14:42: imported `AnalysisStore' is permanently hidden by definition of object AnalysisStore in package inc
> [warn] import xsbti.compile.{ AnalysisContents, AnalysisStore }

2018-02-11 12:14 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=1.x&zinc=pull/487/head&io=1.x&librarymanagement=1.x&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

2018-02-11 12:27 UTC, typesafe-tools commented
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/454/console">is in progress...</a>

2018-02-11 12:34 UTC, typesafe-tools commented
[//]: # (Refs: 1.x-pull/487/head-1.x-1.x-1.x-1.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/454/">has checked</A> the following projects against Scala 2.12, 2.11, 2.10,
tested using sbt-allsources.sh.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.x">1.x                 </A> | sbt/sbt@ccd399e71a9e9e97f7c8f7a2b6acb5ce153ab74c
  zinc              | <A HREF="https://github.com/sbt/zinc/pull/487">pull/487/head       </A> | sbt/zinc@40d526002da6a04e4e3c26b8d780eb804973ad46
  io                | <A HREF="https://github.com/sbt/io/tree/1.x">1.x                 </A> | sbt/io@5efad01da84f4acd60cab08d08625cb32a68fa38
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/1.x">1.x                 </A> | sbt/librarymanagement@e2cb5a0693b055a8855403b147eada430adcc1f4
  util              | <A HREF="https://github.com/sbt/util/tree/1.x">1.x                 </A> | sbt/util@b0baf7de6d76852ed510bd2714980b8858f8f342
  website           | <A HREF="https://github.com/sbt/website/tree/1.x">1.x                 </A> | sbt/website@20480d138c9f131490e24b5e1318b69af0691a84

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=1.x&zinc=pull/487/head&io=1.x&librarymanagement=1.x&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

2018-02-12 07:34 UTC, dwijnand requested changes

2018-02-12 07:34 UTC, dwijnand commented on internal/zinc-core/src/main/scala/sbt/internal/inc/Analysis.scala
> +  Stamp => JavaStamp
Let's consistently prefix classes from xsbti that clash with `X` in all files.

2018-02-12 08:10 UTC, typesafe-tools commented
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/457/console">is in progress...</a>

2018-02-12 08:16 UTC, typesafe-tools commented
[//]: # (Refs: 1.x-pull/487/head-1.x-1.x-1.x-1.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/457/">has checked</A> the following projects against Scala 2.12, 2.11, 2.10,
tested using sbt-allsources.sh.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.x">1.x                 </A> | sbt/sbt@ccd399e71a9e9e97f7c8f7a2b6acb5ce153ab74c
  zinc              | <A HREF="https://github.com/sbt/zinc/pull/487">pull/487/head       </A> | sbt/zinc@e901431ee95c2db209440cdfb6998c3422002621
  io                | <A HREF="https://github.com/sbt/io/tree/1.x">1.x                 </A> | sbt/io@5efad01da84f4acd60cab08d08625cb32a68fa38
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/1.x">1.x                 </A> | sbt/librarymanagement@e2cb5a0693b055a8855403b147eada430adcc1f4
  util              | <A HREF="https://github.com/sbt/util/tree/1.x">1.x                 </A> | sbt/util@b0baf7de6d76852ed510bd2714980b8858f8f342
  website           | <A HREF="https://github.com/sbt/website/tree/1.x">1.x                 </A> | sbt/website@20480d138c9f131490e24b5e1318b69af0691a84

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=1.x&zinc=pull/487/head&io=1.x&librarymanagement=1.x&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

2018-02-12 08:54 UTC, exoego commented
@dwijnand I updated so and rebased commits in https://github.com/sbt/zinc/pull/487/commits/e901431ee95c2db209440cdfb6998c3422002621

2018-02-12 09:18 UTC, dwijnand approved these changes
LGTM. Thank you!

2018-02-12 09:20 UTC, jvican approved these changes

2018-02-12 09:20 UTC, merged