Address #349: Resolve misc warnings
sbt/zinc pull request #500
Opened 2018-02-22 12:15 UTC by exoego

The following 3 types of warning are resolved, to address #349.

* discarded non-Unit value
    * `A => U` instead of `A => Unit` as same as in [IterableLike#foreach](https://github.com/scala/scala/blob/07d61ecf134dbba143531f5a1bd3c1289c437296/src/library/scala/collection/IterableLike.scala#L70)
    * Explicitly add `()` to synchronized block 
* implicit numeric widening
    * `.toInt` is used explicitly.
* The outer reference in this type test cannot be checked at run time.
    * `final` modifier are removed for private case class. https://issues.scala-lang.org/browse/SI-4440

# Before (https://github.com/sbt/zinc/commit/ad46221ca148629df111dbc1561ac348d2b15c9c)

The below commands shows the warnings except `never used`.   I will address `never used` warnings in another PR.

```bash
$ sbt -warn ";clean;compile" | grep -E "\[.*warn.*/zinc" | grep -E -v "is never used" --count
24
```

```bash
$ sbt -warn ";clean;compile" | grep -E "\[.*warn.*/zinc" | grep -E -v "is never used"
[warn] /home/exoego/IdeaProjects/zinc/internal/compiler-bridge/src/main/scala/xsbt/DelegatingReporter.scala:15:15: Unused import
[warn] /home/exoego/IdeaProjects/zinc/internal/compiler-bridge/src/main/scala/xsbt/ExtractUsedNames.scala:75:75: discarded non-Unit value
[warn] /home/exoego/IdeaProjects/zinc/internal/compiler-bridge/src/main/scala/xsbt/ExtractUsedNames.scala:78:23: discarded non-Unit value
[warn] /home/exoego/IdeaProjects/zinc/internal/compiler-bridge/src/main/scala/xsbt/ExtractUsedNames.scala:16:15: Unused import
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-core/src/main/scala/sbt/internal/inc/APIDiff.scala:80:56: implicit numeric widening
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-core/src/main/scala/sbt/internal/inc/APIDiff.scala:81:48: implicit numeric widening
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-core/src/main/scala/sbt/internal/inc/APIDiff.scala:86:37: implicit numeric widening
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/javac/JavacProcessLogger.scala:34:18: discarded non-Unit value
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/javac/JavacProcessLogger.scala:37:18: discarded non-Unit value
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/AnalyzingCompiler.scala:347:56: method libraryJar in trait ScalaInstance is deprecated: see corresponding Javadoc for more information.
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/CompilerArguments.scala:72:67: method compilerJar in trait ScalaInstance is deprecated: see corresponding Javadoc for more information.
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/CompilerArguments.scala:73:65: method otherJars in trait ScalaInstance is deprecated: see corresponding Javadoc for more information.
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/CompilerArguments.scala:98:37: method libraryJar in trait ScalaInstance is deprecated: see corresponding Javadoc for more information.
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/CompilerArguments.scala:141:27: method libraryJar in trait ScalaInstance is deprecated: see corresponding Javadoc for more information.
[warn] /home/exoego/IdeaProjects/zinc/internal/compiler-bridge/src/main/scala/xsbt/API.scala:82:12: method isImplClass in class Symbol is deprecated (since 2.12.0): trait implementation classes have been removed in Scala 2.12
[warn] /home/exoego/IdeaProjects/zinc/internal/compiler-bridge/src/main/scala/xsbt/Analyzer.scala:51:41: method isImplClass in class Symbol is deprecated (since 2.12.0): trait implementation classes have been removed in Scala 2.12
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/javac/JavaCompiler.scala:105:43: method libraryJar in trait ScalaInstance is deprecated: see corresponding Javadoc for more information.
[warn] /home/exoego/IdeaProjects/zinc/internal/compiler-bridge/src/main/scala/xsbt/ClassName.scala:94:33: method isImplClass in class Symbol is deprecated (since 2.12.0): trait implementation classes have been removed in Scala 2.12
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-core/src/main/scala/sbt/internal/inc/APIDiff.scala:155:30: The outer reference in this type test cannot be checked at run time.
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-core/src/main/scala/sbt/internal/inc/APIDiff.scala:156:30: The outer reference in this type test cannot be checked at run time.
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-core/src/main/scala/sbt/internal/inc/APIDiff.scala:157:30: The outer reference in this type test cannot be checked at run time.
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-core/src/main/scala/sbt/internal/inc/APIDiff.scala:158:30: The outer reference in this type test cannot be checked at run time.
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-ivy-integration/src/main/scala/sbt/internal/inc/ZincComponentCompiler.scala:94:30: The outer reference in this type test cannot be checked at run time.
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-benchmarks/src/main/scala/xsbt/ZincBenchmark.scala:352:24: Unused import
```

# After this PR

```bash
$ sbt -warn ";clean;compile" | grep -E "\[.*warn.*/zinc" | grep -E -v "is never used" --count
12
```

```bash
$ sbt -warn ";clean;compile" | grep -E "\[.*warn.*/zinc" | grep -E -v "is never used"
[warn] /home/exoego/IdeaProjects/zinc/internal/compiler-bridge/src/main/scala/xsbt/DelegatingReporter.scala:15:15: Unused import
[warn] /home/exoego/IdeaProjects/zinc/internal/compiler-bridge/src/main/scala/xsbt/ExtractUsedNames.scala:16:15: Unused import
[warn] /home/exoego/IdeaProjects/zinc/internal/compiler-bridge/src/main/scala/xsbt/API.scala:82:12: method isImplClass in class Symbol is deprecated (since 2.12.0): trait implementation classes have been removed in Scala 2.12
[warn] /home/exoego/IdeaProjects/zinc/internal/compiler-bridge/src/main/scala/xsbt/Analyzer.scala:51:41: method isImplClass in class Symbol is deprecated (since 2.12.0): trait implementation classes have been removed in Scala 2.12
[warn] /home/exoego/IdeaProjects/zinc/internal/compiler-bridge/src/main/scala/xsbt/ClassName.scala:94:33: method isImplClass in class Symbol is deprecated (since 2.12.0): trait implementation classes have been removed in Scala 2.12
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/AnalyzingCompiler.scala:347:56: method libraryJar in trait ScalaInstance is deprecated: see corresponding Javadoc for more information.
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/CompilerArguments.scala:72:67: method compilerJar in trait ScalaInstance is deprecated: see corresponding Javadoc for more information.
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/CompilerArguments.scala:73:65: method otherJars in trait ScalaInstance is deprecated: see corresponding Javadoc for more information.
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/CompilerArguments.scala:98:37: method libraryJar in trait ScalaInstance is deprecated: see corresponding Javadoc for more information.
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/CompilerArguments.scala:141:27: method libraryJar in trait ScalaInstance is deprecated: see corresponding Javadoc for more information.
[warn] /home/exoego/IdeaProjects/zinc/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/javac/JavaCompiler.scala:105:43: method libraryJar in trait ScalaInstance is deprecated: see corresponding Javadoc for more information.
[warn] /home/exoego/IdeaProjects/zinc/internal/z [...]

2018-02-22 12:15 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=1.x&zinc=pull/500/head&io=1.x&librarymanagement=1.x&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

2018-02-22 12:19 UTC, typesafe-tools commented
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/490/console">is in progress...</a>

2018-02-22 12:27 UTC, typesafe-tools commented
[//]: # (Refs: 1.x-pull/500/head-1.x-1.x-1.x-1.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/490/">has checked</A> the following projects against Scala 2.12, 2.11, 2.10,
tested using sbt-allsources.sh.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.x">1.x                 </A> | sbt/sbt@e078c126d15a1967910357a1a2e06971a56c66c6
  zinc              | <A HREF="https://github.com/sbt/zinc/pull/500">pull/500/head       </A> | sbt/zinc@947f39ad646ee59bc186bdeb672485155ad75ed4
  io                | <A HREF="https://github.com/sbt/io/tree/1.x">1.x                 </A> | sbt/io@438474e08d34e0ef892e9ee632b028e7563aa466
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/1.x">1.x                 </A> | sbt/librarymanagement@0d21ae6369a3e4054ed434902ea84b2520d21da9
  util              | <A HREF="https://github.com/sbt/util/tree/1.x">1.x                 </A> | sbt/util@85f7d807e116b0247c233259f66b592e05a14ffe
  website           | <A HREF="https://github.com/sbt/website/tree/1.x">1.x                 </A> | sbt/website@c605957d2356e43c37a99831fafd484fa13b8bda

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=1.x&zinc=pull/500/head&io=1.x&librarymanagement=1.x&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

2018-02-22 14:03 UTC, dwijnand commented
I'm concerned about the type-signature change to avoid the non-unit discarding, as well as opening those case classes for extention..

Let's see first what CI thinks.

2018-03-01 01:33 UTC, exoego commented
@dwijnand 
https://platform-ci.scala-lang.org/sbt/zinc
Looks like Drone CI got stuck for days on several PRs...
Could you restart pending builds ?

2018-03-01 07:39 UTC, dwijnand commented
for some reason I can't restart any builds. opened https://github.com/sbt/zinc/issues/504.

2018-03-01 09:56 UTC, dwijnand commented
Drone CI fix, PR validation restarted @exoego

2018-03-05 23:24 UTC, jvican approved these changes
LGTM, thanks @exoego :smile:.

2018-03-06 11:28 UTC, dwijnand requested changes
Thanks @exoego!

2018-03-06 11:28 UTC, dwijnand approved these changes

2018-03-06 11:28 UTC, merged