Upgrade scalapb machinery to modern version
sbt/zinc pull request #713
Opened 2019-11-02 14:52 UTC by slandelle

Motivation:

Protobuf machinery currently uses com.trueaccord.scalapb:compilerplugin which is the old groupId and is not available for Scala 2.13.

Modifications:

* Upgrade com.thesamet:sbt-protoc to 0.99.26
* Switch to com.thesamet.scalapb:compilerplugin 0.9.3
* Remove com.google.protobuf:protobuf-java forced version upgrade as version now pulled is 3.8.0

Note:

* scala-maven-plugin test suite passes with Scala 2.12 build with those changes.

Result:

Zinc now uses a modern version of scalapb, where a crosscompiled version for Scala 2.13 is available.

2019-11-02 14:52 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=pull/713/head&io=develop&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

2019-11-02 15:28 UTC, eed3si9n commented
Thanks @slandelle!

2019-11-02 15:28 UTC, eed3si9n requested changes
Could you add mima exclusion rules for `"sbt.internal.inc.schema.*"` until `mimaReportBinaryIssues` passes?

2019-11-02 16:56 UTC, eed3si9n commented on build.sbt
> +        exclude[IncompatibleSignatureProblem]("sbt.internal.inc.MiniSetupUtil.equivCompileSetup")
The trailing comma here was intentional. It tends to result in cleaner diff.

2019-11-02 17:59 UTC, slandelle commented
@eed3si9n Any idea what I'm doing wrong with mima?

```
[info] Compiling 83 Scala sources and 6 Java sources to /home/travis/build/sbt/zinc/internal/zinc-persist/target/scala-2.12/classes ...
[error]  * the type hierarchy of class sbt.internal.inc.zprof.InitialChanges#InitialChangesLens is different in current version. Missing types {com.trueaccord.lenses.ObjectLens}
[error]    filter with: ProblemFilters.exclude[MissingTypesProblem]("sbt.internal.inc.zprof.InitialChanges$InitialChangesLens")
```

but I've added to zincPersist:

```
exclude[MissingTypesProblem]("sbt.internal.inc.zprof.*")
```

2019-11-02 20:45 UTC, slandelle commented
> Could you add mima exclusion rules for `"sbt.internal.inc.schema.*"` until `mimaReportBinaryIssues` passes?

@eed3si9n fixed!

2019-11-02 20:46 UTC, eed3si9n approved these changes

2019-11-02 20:47 UTC, slandelle commented
@eed3si9n BTW, why is dev HEAD version 1.3.0-SNAPSHOT while 1.3.1 is out?

2019-11-02 20:48 UTC, eed3si9n commented
I guess that's just how sbt-dynver calculates the version until we tag it. develop would be Zinc 1.4.x or 2.x.

2019-11-04 09:18 UTC, jvican approved these changes
LGTM :+1:

2019-11-04 09:18 UTC, merged

2019-11-04 09:20 UTC, slandelle commented
Thanks for merging!

2019-11-04 09:31 UTC, dwijnand commented
> I guess that's just how sbt-dynver calculates the version until we tag it. develop would be Zinc 1.4.x or 2.x.

You need to change the `if ((ThisBuild / isSnapshot).value) "1.3.0-SNAPSHOT"` in `build.sbt`.  And you could even use `isVersionStable` instead of `isSnapshot`.