Cleanup parts of the VirtualFile-related code
sbt/zinc pull request #820
Opened 2020-07-08 07:13 UTC by dwijnand

* Rename VirtualFileWrap/XsbtPlainFile/XsbtVirtualFile to
  AbstractZincFile/ZincPlainFile/ZincVirtualFil;
* Give 2/3 of FileConverter's default implementations & use the;
* Rework BasicVirtualDirectory & BasicMemoryFile to avoid needless
  Option and BasicVirtualDirectory boxing, & use structural sharing;
* Cleanup some of VirtualFile's docs.

Subset of #819

2020-07-08 07:13 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=pull/820/head&io=develop&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

2020-07-09 21:02 UTC, eed3si9n requested changes

2020-07-09 21:02 UTC, eed3si9n commented on internal/compiler-interface/src/main/java/xsbti/BasicVirtualFileRef.java
> +        if (Objects.equals(parent, "")) {
```
scala> java.util.Objects.equals(null, "")
res0: Boolean = false
```

so wouldn't this return different result for `null`?

2020-07-09 21:11 UTC, dwijnand commented on internal/compiler-interface/src/main/java/xsbti/BasicVirtualFileRef.java
> +        if (Objects.equals(parent, "")) {
Yeah, but `parent` never is `null`, so I dropped that first.

But the thing here is equals vs `==`, in Java, where `==` means reference equality.  I _assume_/hope there's only 1 `""`, or at least for the literal `""`, within a JVM execution, but I wasn't sure so went with the safer option.

WDYT?

2020-07-10 01:19 UTC, eed3si9n commented on internal/compiler-interface/src/main/java/xsbti/BasicVirtualFileRef.java
> +        if (Objects.equals(parent, "")) {
You're right on this one.

```
eval new String("") eq ""
<eval>:1: warning: comparing a fresh object using `eq' will always yield false
new String("") eq ""
               ^
[info] ans: Boolean = false
```

2020-07-10 01:21 UTC, eed3si9n approved these changes

2020-07-10 05:40 UTC, merged